name: sirteefy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  ionicons: ^0.2.2
  flutter_svg: ^2.0.17
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.1
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  firebase_core: ^4.1.0
  dartz: ^0.10.1
  skeletonizer: ^2.1.0+1
  cloud_firestore: ^6.0.1
  url_launcher: ^6.3.1
  oktoast: ^3.4.0
  get_it: ^8.0.3
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/fira_code/FiraCode-Light.ttf
        - asset: assets/fonts/fira_code/FiraCode-Regular.ttf
        - asset: assets/fonts/fira_code/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/fira_code/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/fira_code/FiraCode-Bold.ttf
          weight: 700
