name: sirteefy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  responsive_framework: ^1.5.1
  ionicons: ^0.2.2
  flutter_svg: ^2.0.17
  auto_size_text: ^3.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/pngs/
    - assets/svgs/
  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/fira_code/FiraCode-Light.ttf
        - asset: assets/fonts/fira_code/FiraCode-Regular.ttf
        - asset: assets/fonts/fira_code/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/fira_code/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/fira_code/FiraCode-Bold.ttf
          weight: 700
