// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqqeeCTDzv4kRXfv4MnZGjX0qWBhwf0CI',
    appId: '1:421586403717:web:e4b72eea869f9104a344ec',
    messagingSenderId: '421586403717',
    projectId: 'porrrrtf',
    authDomain: 'porrrrtf.firebaseapp.com',
    storageBucket: 'porrrrtf.appspot.com',
    measurementId: 'G-FQHFV2ZY0K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTG1fFOw9du-3rKtqa1wuqpdFmz3SLlhQ',
    appId: '1:421586403717:android:15f247116f3da507a344ec',
    messagingSenderId: '421586403717',
    projectId: 'porrrrtf',
    storageBucket: 'porrrrtf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnfTXiFPvHHuW_4_KYOH-vE45oQLan4lA',
    appId: '1:421586403717:ios:eec305cff32aa828a344ec',
    messagingSenderId: '421586403717',
    projectId: 'porrrrtf',
    storageBucket: 'porrrrtf.appspot.com',
    iosBundleId: 'com.example.sirteefy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbehl-vmjU0oGtopepgfW1GFToK2NTho4',
    appId: '1:421586403717:web:ee651eef07247422a344ec',
    messagingSenderId: '421586403717',
    projectId: 'porrrrtf',
    authDomain: 'porrrrtf.firebaseapp.com',
    storageBucket: 'porrrrtf.appspot.com',
    measurementId: 'G-6N1FT22PGN',
  );
}