// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-0_tWckdIhgg0dpPqUwCOVnB9_RWuD-4',
    appId: '1:250836487682:web:5477dd56f040d9b507211b',
    messagingSenderId: '250836487682',
    projectId: 'sirteefy-f3980',
    authDomain: 'sirteefy-f3980.firebaseapp.com',
    storageBucket: 'sirteefy-f3980.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxE3uGoEdPzufXCmu7gCjBsmoz3ZSO96Y',
    appId: '1:250836487682:android:9789f0ebf0efa9c907211b',
    messagingSenderId: '250836487682',
    projectId: 'sirteefy-f3980',
    storageBucket: 'sirteefy-f3980.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpU_poZJeripqqKDRsZrsEBZ_4KmXULOg',
    appId: '1:250836487682:ios:39eb2c52ddee432007211b',
    messagingSenderId: '250836487682',
    projectId: 'sirteefy-f3980',
    storageBucket: 'sirteefy-f3980.firebasestorage.app',
    iosBundleId: 'com.example.sirteefy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbehl-vmjU0oGtopepgfW1GFToK2NTho4',
    appId: '1:421586403717:web:ee651eef07247422a344ec',
    messagingSenderId: '421586403717',
    projectId: 'porrrrtf',
    authDomain: 'porrrrtf.firebaseapp.com',
    storageBucket: 'porrrrtf.appspot.com',
    measurementId: 'G-6N1FT22PGN',
  );
}